In [1]:
import numpy as np 

In [5]:
#create arrays 

arr1 = np.array([1,2,3,4,5])
b = np.zeros((2,3))
c = np.ones((2,3))
d = np.arange(0, 10, 2)       # Values from 0 to 8 with step 2
e = np.linspace(0,3,7)
f = np.eye(3,3) #identify matrix
g = np.random.rand(2,4) #random values between 0 and 1

print("Array 1:", arr1)
print("Array 2:", b)
print("Array 3:", c)
print("Array 4:", d)
print("Array 5:", e)
print("Array 6:", f)
print("Array 7:", g)


Array 1: [1 2 3 4 5]
Array 2: [[0. 0. 0.]
 [0. 0. 0.]]
Array 3: [[1. 1. 1.]
 [1. 1. 1.]]
Array 4: [0 2 4 6 8]
Array 5: [0.  0.5 1.  1.5 2.  2.5 3. ]
Array 6: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array 7: [[0.80167095 0.70469961 0.67915134 0.83457202]
 [0.60083428 0.7613285  0.59609642 0.83775288]]


In [ ]:
# Array Attributes

arr2 = np.array([[1,2,3],[5,6,9]])

print("arr2size:",arr2.size)
print("arr2shape:",arr2.shape)
print("arr2dimensions:",arr2.ndim)
print("arr2datatypes",arr2.dtype)
#shape → Number of rows and columns.
#ndim → Number of dimensions.
#size → Total number of elements.
#dtype → Data type of elements.


arr2size: 6
arr2shape: (2, 3)
arr2dimensions: 2
arr2datatypes int64


In [ ]:
#Indexing and Slicing
arr3 = np.array([10,20,30,40,50])
print("arr 3rd element:", arr3[2])
print("arr range of elements:",arr3[1:4]) #from index 1 to 3
print("arr last element:",arr3[-1])
print("every 3rd element:",arr3[::3]) #from start to end with step 3

arr3rd element: 30
arr3 range of elements: [20 30 40]
arr last emlement: 50
every 3rd element: [10 40]


In [10]:
#2D Indexing
arr4 = np.array([[1,2,3],
                [4,5,6],[7,2,5]])
print("specific element of 2d array:",arr4[1,2])
print("complete column of 2d array :",arr4[:,2])
print("complete row of 2d array :",arr4[1,:])

specific element of 2d array: 6
complete column of 2d array : [3 6 5]
complete row of 2d array : [4 5 6]


In [ ]:
#Reshaping Arrays

arr5 = np.arange(12)
print(arr5)
arr_b = arr5.reshape(3,4)
print(arr_b)
arr_c = arr5.reshape(2,6)
print(arr_c)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ValueError: cannot reshape array of size 12 into shape (10,1)