In [1]:
import numpy as np 

In [5]:
#create arrays 

arr1 = np.array([1,2,3,4,5])
b = np.zeros((2,3))
c = np.ones((2,3))
d = np.arange(0, 10, 2)       # Values from 0 to 8 with step 2
e = np.linspace(0,3,7)
f = np.eye(3,3) #identify matrix
g = np.random.rand(2,4) #random values between 0 and 1

print("Array 1:", arr1)
print("Array 2:", b)
print("Array 3:", c)
print("Array 4:", d)
print("Array 5:", e)
print("Array 6:", f)
print("Array 7:", g)


Array 1: [1 2 3 4 5]
Array 2: [[0. 0. 0.]
 [0. 0. 0.]]
Array 3: [[1. 1. 1.]
 [1. 1. 1.]]
Array 4: [0 2 4 6 8]
Array 5: [0.  0.5 1.  1.5 2.  2.5 3. ]
Array 6: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array 7: [[0.80167095 0.70469961 0.67915134 0.83457202]
 [0.60083428 0.7613285  0.59609642 0.83775288]]


In [ ]:
# Array Attributes

arr2 = np.array([[1,2,3],[5,6,9]])

print("arr2size:",arr2.size)
print("arr2shape:",arr2.shape)
print("arr2dimensions:",arr2.ndim)
print("arr2datatypes",arr2.dtype)
#shape → Number of rows and columns.
#ndim → Number of dimensions.
#size → Total number of elements.
#dtype → Data type of elements.


arr2size: 6
arr2shape: (2, 3)
arr2dimensions: 2
arr2datatypes int64


In [ ]:
#Indexing and Slicing
arr3 = np.array([10,20,30,40,50])
print("arr 3rd element:", arr3[2])
print("arr range of elements:",arr3[1:4]) #from index 1 to 3
print("arr last element:",arr3[-1])
print("every 3rd element:",arr3[::3]) #from start to end with step 3

arr3rd element: 30
arr3 range of elements: [20 30 40]
arr last emlement: 50
every 3rd element: [10 40]


In [10]:
#2D Indexing
arr4 = np.array([[1,2,3],
                [4,5,6],[7,2,5]])
print("specific element of 2d array:",arr4[1,2])
print("complete column of 2d array :",arr4[:,2])
print("complete row of 2d array :",arr4[1,:])

specific element of 2d array: 6
complete column of 2d array : [3 6 5]
complete row of 2d array : [4 5 6]


In [ ]:
#Reshaping Arrays

arr5 = np.arange(12)
print(arr5)
arr_b = arr5.reshape(3,4)
print(arr_b)
arr_c = arr5.reshape(2,6)
print(arr_c)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
arr_d =arr5.flatten()
print(arr_d) #flatten() returns a copy.
arr_e = arr5.ravel()
print(arr_e)
#ravel() returns a flattened view of the array. It does not create a copy of the original array. 
# If you modify the raveled array, it will affect the

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
#Mathematical Operations
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [22]:
#Universal Functions (ufuncs)
arr6 = np.array([2,3,4])
print(np.sqrt(arr6))
print(np.exp(arr6))
print(np.log(arr6))
print(np.sin(arr6))
print(np.cos(arr6))

[1.41421356 1.73205081 2.        ]
[ 7.3890561  20.08553692 54.59815003]
[0.69314718 1.09861229 1.38629436]
[ 0.90929743  0.14112001 -0.7568025 ]
[-0.41614684 -0.9899925  -0.65364362]


In [ ]:
# Aggregation Functions
arr7 = np.array([[1,2,3,4,5],[5,7,82,4,7]])
print(np.sum(arr7))
print(np.sum(arr7, axis=1)) #axis 1 means sum along the rows, axis 0 means sum along the columns    
print(np.sum(arr7, axis=0))

print(np.mean(arr7))
print(np.median(arr7))
print(np.std(arr7))
print(np.max(arr7))
print(np.min(arr7))
print(np.var(arr7))

120
[ 15 105]
[ 6  9 85  8 12]
12.0
4.5
23.40512764331782
82
1
547.8


In [36]:
#Broadcasting
arr8 = np.array([1,2,3])
print(arr8 + 5) #broadcasting adds 5 to each element of the array

arr9 = np.array([2,5,8])
arr10 = np.array([4,6,9])
arr11 = arr9+arr10
print(arr11)

[6 7 8]
[ 6 11 17]


In [48]:
#Boolean Masking
arr12 = np.array([1,2,5,64,55,8,96])
print(arr12 > 5)
print(arr12 >= 5)
print(arr12[arr12>5])

print(arr12 [arr12 % 2 == 0])
print(arr12[(arr12 >= 5) & (arr12 <= 10)])
print(arr12[(arr12 >= 5) | (arr12 <= 10)])
arr12[arr12 > 30] = 100
print(arr12)

[False False False  True  True  True  True]
[False False  True  True  True  True  True]
[64 55  8 96]
[ 2 64  8 96]
[5 8]
[ 1  2  5 64 55  8 96]
[  1   2   5 100 100   8 100]
