In [ ]:
import numpy as np

#Sorting 
arr1 = np.array([3,1,5,8,1,4])
print("sorted array:",np.sort(arr1))


sorted array: [1 1 3 4 5 8]


In [4]:
print(np.argsort(arr1)) #returns the indices that would sort the array
print(np.argmax(arr1))

[1 4 0 5 2 3]
3


In [ ]:
#Combining Arrays
a = np.array([1,2])
b = np.array([3,4])
arr2 = np.array([[1,2],
              [3,4]])

arr3 = np.array([[5,6],
              [7,8]])

print(np.concatenate((a,b)))
print(np.concatenate((arr2,arr3),axis = 0)) #rows are stacked on top of each other
print(np.concatenate((arr2,arr3), axis=1)) # columns are stacked next to each other


[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
print(np.vstack((arr2,arr3))) #vertical stacking
print(np.hstack((arr2,arr3))) #horizontal stacking  

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [18]:
#Matrix Operations
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A@B)
print(A.T)
print(B.T)
print(np.linalg.inv(A))
print(np.linalg.det(A))

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [19]:
#Useful Utility Functions
print(np.unique(a))
print(np.where(a > 3))
print(np.clip(a,2,4))


[1 2]
(array([], dtype=int64),)
[2 2]


In [25]:
#Copy vs View
d= np.array([1,2,3])
d[0] = 100
print(d)   # Original array is modified
print(d.copy())   # Independent copy #nayi memory location pe copy banegi
print(d.view())   # Shares the same data # pointer/reference same memory location pe point karega

[100   2   3]
[100   2   3]
[100   2   3]


In [26]:
#Isnan
e = np.array([1,2,np.nan,4])
print(np.isnan(e))

[False False  True False]


1. Why is NumPy Faster than Python Lists? ⭐⭐⭐⭐⭐

This is one of the most common interview questions.

Python List
lst = [1, 2, 3, 4]
Stores references (pointers) to Python objects.
Elements can have different data types.
More memory usage.
Slower due to Python's dynamic typing.
NumPy Array
arr = np.array([1,2,3,4])
Stores data in contiguous memory.
All elements have the same data type.
Optimized C implementation.
Uses SIMD (Single Instruction Multiple Data) and vectorized operations.

Interview Answer:

NumPy is faster because it stores homogeneous data in contiguous memory and performs operations using optimized C code instead of Python loops.

2. Vectorization ⭐⭐⭐⭐⭐

Instead of writing loops, NumPy performs operations on the entire array.

Without NumPy

result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

With NumPy

result = a + b

Benefits

Less code
Faster execution
Better readability

3. Memory Layout

NumPy stores arrays continuously.

Imagine

1 2 3 4 5

Memory

100
104
108
112
116

Continuous memory makes cache access efficient, which improves performance.

4. reshape vs resize

✅ reshape()
Sirf shape change karta hai.
Original array change nahi hota.
Elements ki count same rehti hai.
a = np.array([1,2,3,4,5,6])

b = a.reshape(2,3)
a → [1 2 3 4 5 6]

b →

[[1 2 3]
 [4 5 6]]
✅ resize()
Original array ko modify karta hai.
Shape change karta hai.
Zarurat pade to elements ki count bhi badha ya ghata sakta hai.
a = np.array([1,2,3])

a.resize((5,))

print(a)

Output:

[1 2 3 0 0]

5. cumsum()

Running total.

a = np.array([1,2,3,4])

np.cumsum(a)

Output

[1 3 6 10]

Because
1

1+2

1+2+3

1+2+3+4

6. cumprod()

Running multiplication.

a = np.array([1,2,3,4])

np.cumprod(a)

Output

[1 2 6 24]